[contract.deployments.arbitrum-sepolia]
network = "arbitrum-sepolia"
no_activate = false
deployer_address = "0xcEcba2F1DC234f70Dd89F2041029807F8D03A990"

[workspace.networks.arbitrum-sepolia]
endpoint = "https://sepolia-rollup.arbitrum.io/rpc"
